# Generated by Django 4.2.1 on 2023-05-24 15:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telegram_id', models.IntegerField(unique=True)),
                ('username', models.CharField(max_length=64, null=True, verbose_name='User Name')),
                ('first_name', models.CharField(max_length=256, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Last Name')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='email')),
                ('is_admin', models.BooleanField(blank=True, default=False, null=True, verbose_name='Администратор')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО мастера')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Наименование салона')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес Салона')),
                ('time_open', models.TimeField(verbose_name='время открытия')),
                ('time_close', models.TimeField(verbose_name='время закрытия')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Имя услуги')),
                ('price', models.CharField(max_length=10, verbose_name='Стоимость услуги')),
                ('salon', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='salon_service', to='beautycitybot.salon', verbose_name='Салон')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='YYYY-MM-DD', verbose_name='Дата посещения')),
                ('time_visit', models.IntegerField(choices=[(0, '09:00 – 10:00'), (1, '10:00 – 11:00'), (2, '11:00 – 12:00'), (3, '12:00 – 13:00'), (4, '13:00 – 14:00'), (5, '15:00 – 16:00'), (6, '16:00 – 17:00'), (7, '17:00 – 18:00'), (8, '18:00 – 19:00')], null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules_user', to='beautycitybot.client', verbose_name='Имя клиента')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_master', to='beautycitybot.master', verbose_name='Мастер')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_salon', to='beautycitybot.salon', verbose_name='Салон')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_service', to='beautycitybot.service', verbose_name='Услуга')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='master',
            name='salon',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='salon', to='beautycitybot.salon', verbose_name='Салон где работает Мастер'),
        ),
        migrations.AddField(
            model_name='master',
            name='services',
            field=models.ManyToManyField(to='beautycitybot.service'),
        ),
    ]
