# Generated by Django 4.2.1 on 2023-05-26 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beautycitybot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
    ]
